apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: {{ index .Values "local-mesh-bookinfo-namespace" }}
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: details